# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blogapi
    tier: backend
  name: blogapi-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapi
      tier: backend
  template:
    metadata:
      labels:
        app: blogapi
        tier: backend
    spec:
      containers:
      - name: blogapi
        image: knoxknot/blogapi:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: blogapiport
          containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 15Mi
          requests:
            cpu: 10m
            memory: 10Mi

# Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blogapi
    tier: backend
  name: blogapi-svc
  namespace: default
spec:
  selector:
    app: blogapi
    tier: backend
  ports:
  - name: blogapi
    protocol: TCP
    port: 8080
    nodePort: 30080
  type: NodePort
